### ISSUE TITLE
Problems downloading TiVo shows

### ISSUE THREAD

**Issue by burdell1** [dscottbuch/cTiVo#105]
I am having a problem where, when I try to download episodes from my Tivo, some download with no problems and others have errors and end up not downloading. I can send a copy of my log to you to see if you have any suggestions.

**Comment by burdell1** [comment]
where are the logs at? i thought i knew but i am not seeing them

**Comment by mackworth** [comment]
If you're using the latest beta (version 8, which I would recommend), then just see the Help menu.  If not they are in <your home dir>/Library/Logs/cTiVo.  Best to set the Debug level to Detail before running the show that has a problem.

**Comment by burdell1** [comment]
ok...i'll post the logs...it seems it happens when i have it set to 'mark' commercials.

**Comment by burdell1** [comment]
can i send the logs as a private message?

**Comment by mackworth** [comment]
Sure. Do a right-click on the cTiVo log folder, compress and then send as an email to mackworth@aol.com

**Comment by mackworth** [comment]
So, I notice this pattern
````
2015-05-28 00:14:50 Removing Service: DVR-B53C
2015-05-28 01:14:58 Found Service DVR-B53C
2015-05-28 02:00:56 Removing Service: DVR-B53C
2015-05-28 02:30:58 Found Service DVR-B53C
2015-05-28 03:08:37 Removing Service: DVR-B53C
2015-05-28 03:38:39 Found Service DVR-B53C
2015-05-28 04:16:04 Removing Service: DVR-B53C
2015-05-28 04:46:09 Found Service DVR-B53C
2015-05-28 05:52:39 Removing Service: DVR-B53C
2015-05-28 05:52:44 Found Service DVR-B53C
2015-05-28 06:30:01 Removing Service: DVR-B53C 
2015-05-28 06:50:50 Found Service DVR-B53C````

So that's saying that about once an hour to 1.5 hrs, your TiVo is dropping off the network (as far as being seen by your Mac) for almost exactly 20 minutes, 30 minutes or an hour. So any thoughts why this might be?  Is cTiVo's option to not sleep during processing on? Do you have any other network issues. Also what is the throughput you're seeing on the screen? Doesn't look very high.

**Comment by mackworth** [comment]
@burdell1 Any update?

**Comment by burdell1** [comment]
at first i thought it was totally fixed (thank you btw!). It seems that they download ok now...one little minor thing that is still going on is that sometimes when it is marking the commercials, it says 'failed'.' Not sure what might be causing this. It really is a minor thing, but i would love to be able to do it. Thanks again!

**Comment by mackworth** [comment]
Comskip is not a stable piece of code, especially as the only Mac version is a few years old, so it frequently fails. On the other hand, when that happens, cTiVo just skips doing the commercials, giving you a notification, but still finishing the file. 

So if you're seeing shows fail entirely, then there's a different problem. I'd suggest running the logs at Detail for a while and when you have one that fails, send it to me again.

**Comment by burdell1** [comment]
ok..i'm going to be out of town until Monday, but i will send you a log then..thanks!

**Comment by burdell1** [comment]
ok i have a new problem..it seems like this one episode transfers completely, but when it is 3/4 through the episode i just get a black screen. I know the one on the tv shows the whole thing, but wasn't sure why it was doing it. i'll send you the log to that email address if thats ok

**Comment by mackworth** [comment]
That's fine to send to me, but there's probably not much I can do. Typically that's due to a digital glitch at that point, although usually the file just finishes, unusual for it to pause for the rest of the file.  If you look at the video on the TV at that moment, you may even see a momentary glitch on the screen. It's believed the encryption routines are more sensitive, so they get off track and create junk in the transmitted file.

**Comment by mackworth** [comment]
Assuming that it's just a occasional problem with comskip. If not, let me know.
