### ISSUE TITLE
HOW TO transfer TiVo Premiere XL shows to 32" HDTV in RV?

### ISSUE THREAD

**Issue by BrokerDon** [dscottbuch/cTiVo#106]
What is the most efficient way to watch our TiVo recordings that are on our TiVo Premiere XL on our 12V 32" Jensen HDMI HDTV in our RV?  Preferably I'd like the shows playing from my iPad 128GB Air 2 to our HDTV via my Apple Lightning to HDMI cable.  Alternatively I could play them from my 16GB / 500GB SSD early 2011 early 2011 17" MacBook Pro 2.2Ghz Core i7 but it uses a LOT more power (not good when we're Off Grid) and is noisy during video playback.

Sadly, the iOS TiVo app blocks ALL playback to the Apple Lightning to HDMI cable... A restriction which wasn't obvious until AFTER we bought and installed a TiVo Stream at our Gigibit Ethernet / ASUS RT-AC66U 802.11ac wired house.

Thanks for your help!

**Comment by mackworth** [comment]
Well, I can't help with live streaming, but if your goal is to have every recorded show available on the iPad, say by the next morning**, you can set it up as follows:
1) Set your preferred options; my choices would be AppleTV, Mark Commercials, include subtitles, copy to iTunes and autosync
2) Create a manual subscription with `ALL` as the show name
3) set your Mac to wakeup at 1:00A and tell cTiVo to start processing at 1:00A (off otherwise)
4) Tell iTunes the IPad should get all videos.
TiVo will record whatever you tell it to, cTiVo will wake up and transfer all the shows to the Mac, then ask iTunes to sync and in the morning you should have all your shows available to play with Apple's Video app, which will play nicely over the HDMI.  Obviously even with 128G, space will eventually become an issue, so you'll have to manually delete after viewing on the iPad and Mac.

In re-reading, not sure if you're talking about while on the road. In that more complicated scenario, you have two choices, either set up a Mac at home doing the above, but putting the shows into (for example) Dropbox, syncing to a remote Mac. That has a big bandwidth advantage (e.g. 1/4) over the alternative, which is to set your router to allow remote access direct to your TiVo by cTiVo running on your MBP.

Let me know if this works for you.

** (except for copy-protected shows such as HBO, or on TimeWarner, just about all of them)

**Comment by BrokerDon** [comment]
Thanks for the SUPER FAST response!  Sounds like it should get the shows we want to my iPad Air 2 so we can take them when we travel.  Best shows to take on vacation are travel adventure shows like Motion for our destinations.  We did this on our recent trip to Yosemite but our only viewing option was to watch it on the iPad Air 2's 9.5" screen... instead of our RV's 12 volt 32" LED 1080p HDTV.

I'll let you know how this worked out next week after our next RV trip.  I already converted a 30 minute Motion show to H264 High Quality and transferred it to a 128GB USB key to see if our 32" HDTV will play it directly.  This will save the iPad's 128GB memory and power if it works.

Wish me luck!

**Comment by mackworth** [comment]
Hope it goes well!  You might experiment with different formats. The trade off of quality v size can be surprising.

**Comment by BrokerDon** [comment]
Will do.  Definitely want 1080p on our 32² HDTV if the show was recorded at
that resolution... Especially since I have a 128GB USB stick for videos.

**Comment by mackworth** [comment]
How'd this work out for you?
