### ISSUE TITLE
HD Format

### ISSUE THREAD

**Issue by StevenMR** [dscottbuch/cTiVo#118]
What cTivo format do I want to use to get an HD program from my Premier to my iMac so I can burn it (in HD) to a BluRay disc. I have the appropriate burning software/hardware.

**Comment by mackworth** [comment]
For best/fastest/easiest process, you might use cTiVo to download/decrypt and your burning software to transcode. Try downloading one with "Decrypted TiVo show" format, which does no conversion at all, and then see if your bluray software can read it. If so, that's probably your best bet rather than trying to get cTiVo to produce exactly the right format that will obviate the need for your bluray software to convert it again.
