### ISSUE TITLE
Can cTivo convert it's own downloaded files to other formats?

### ISSUE THREAD

**Issue by kstella** [dscottbuch/cTiVo#125]
Still not sure which format is best to save for *all* purposes for future conversions to  iTunes, Quicktime, or pushing back to TV in some manner.

**Comment by Mudflapper** [comment]
I always download as decrypted TiVo. I'm teaching myself how to edit video in Final Cut Pro, so I use MPEG Streamclip to convert that MPEG video into Apple ProRes LT so I can edit natively and export as any format I want down the road. However, I believe that requires the MPEG 2 codec. (It's been awhile and I can't remember if I purchased that separately.)

I wish I could somehow use cTivo to download and convert to ProRes simultaneously, but it appears Mencoder can't handle that. Eventually I'd like to set up an Automator folder action to watch for files from cTivo and convert them automatically.

Steve

**Comment by mackworth** [comment]
@Mudflapper Apparently ffmpeg can. In searching the web, this incantation was recommended:
ffmpeg -i input.mov -vcodec prores -profile:v 1 -acodec  pcm_s16le output.mov
You'll have to install ffmpeg as we don't ship it inside cTiVo.

A couple of references to check:
  https://trac.ffmpeg.org/wiki/Encode/VFX
  http://codecs.multimedia.cx/?p=388

I created a Format you can import to experiment with, but I haven't tried it myself. As github only supports text files, after downloading, please rename from `.txt` to `.plist` before doing an Import Formats in cTiVo:
[ProRes LT.plist](https://github.com/dscottbuch/cTiVo/files/10892/ProRes.LT.txt)

**Comment by Mudflapper** [comment]
No way! Thanks so much!

I’ll give it a try this weekend and report back.

Thanks again,

Mudflapper

**Comment by mackworth** [comment]
@kstella Personally, I mostly use the AppleTV format. It's fast, small, and has many of the fields for pyTiVo return trip built in.  (If you want the rest, be sure to enable the metadata, and then carry the ".txt" file along with you.  Note that we'll push the video directly into iTunes if you like.

**Comment by kstella** [comment]
pyTivo? is that something to push files up to Tivo? I ‘upgraded’ to Roamio and my old tools died.

**Comment by mackworth** [comment]
Exactly. It's a great product. Can be a little tricky to install, but then it works really well. It's here: [PyTivo download]{https://github.com/wmcbrine/pytivo/archive/master.zip). [Some documentation here.](https://github.com/wmcbrine/pytivo) Tech support works through TiVocommunity forum.

**Comment by kstella** [comment]
Many Thanks!

**Comment by Mudflapper** [comment]
@mackworth I've been using your ProRes LT format and it's been working without a hitch. The file sizes are a bit larger (~50GB for an hour instead of ~40GB when I used to use cTivo to download a decrypted MPEG2 then convert to ProRes LT with MPEG Streamclip) but otherwise, it's perfect.

It saves me a couple steps and I couldn't be more pleased. I can just leave my iMac running and it will automatically save my subscribed shows as ProRes LT. Next, I'm going to try to figure out how to use Automator and folder actions to watch a folder for new ProRes files and automatically import them into Final Cut Pro X. I'll report back if I figure it out—might be a while, I'm swamped lately.

Thanks again!
