### ISSUE TITLE
Add ability to only see content on my TiVo that has/has not been downloaded

### ISSUE THREAD

**Issue by mortax** [dscottbuch/cTiVo#137]
i'm now using cTiVo to download content for viewing via plex. i'd love to be able to easily switch between seeing all shows on my TiVo and those that haven't been downloaded.

any chance you could add a UI element (button/toggle/etc.) to filter the view?

**Comment by mackworth** [comment]
so, we currently track what's been downloaded through two mechanisms: completed items in the queue, and by attaching a specific metadata to the files in the OS (as long as they are not deleted or moved off the Mac's view). The first is indicated by a checkmark in the Queued column (albeit doesn't distinguish between to-be-done and completed/failed), so that can be sorted, and the second is by the bold-facing of line items. Does that boldfacing not provide the info you need?

**Comment by mortax** [comment]
sorry for the delayed reply.

yes, your suggestions do tell me how to know what has/has not been downloaded. i was really hoping for a filter so that i could easily see just one *or* the other. perhaps isn't not something everyone will want, but i'd sure love it. ;-)

**Comment by mackworth** [comment]
Added OnDisk column in 2.5, allowing sorting by whether we can currently see downloaded copy of disk.
