### ISSUE TITLE
Downloads failing even after Tivo restarted

### ISSUE THREAD

**Issue by davidtkearns** [dscottbuch/cTiVo#148]
Symptoms along lines of this [FAQ item](https://code.google.com/p/ctivo/wiki/FAQ):

"My shows aren't downloading; although I can see the list and can request a download, every show tries several times, then gives up.

> This symptom may mean that your TiVo's internal file server has crashed. It's quite delicate, and certain combinations of operations (which we try to avoid) can cause problems. Try restarting your TiVo (TiVo Central > Messages & Settings > Restart or Reset System > Restart the TiVo; doing this while recording will cancel recording) and see if the problem is fixed. If it does and yet reoccurs later, let us know."

Restarting the Tivo helps - it will download one or two more programs, then the failures happen again. It worked great until a few days ago - is there anything within last update causing this? Anything else I can do apart from restarting my Tivo every day?

I'm using an Australian series 3 HD Tivo.

**Comment by mackworth** [comment]
Well, frankly I'm surprised that an Australian tivo worked at all, as we don't support the transport that it requires.  Nonetheless, can you set the Debug level to Detail, record a couple of failures, and post it somewhere like DropBox and put a link here (github won't post anything other than images)?  I'll be happy to take a look.

**Comment by davidtkearns** [comment]
Cheers Hugh. Here's the log file with Detail debug turned on, trying again with a couple of shows:
https://dl.dropboxusercontent.com/u/12664453/com.cTiVo.cTiVo%202015-12-09%2007-04.log

**Comment by mackworth** [comment]
So, what you can see there is:
  12/9 6PM: some failures and a pause
  12/9 7PM; two good transfers
  12/9 9:20pm: partial transfers
You'll see a warning message of `damaged/incomplete`. This is generated when the TiVo tells us it's finished sending the file, but it's not nearly long enough (less than 85% delivered).
  12/10 midnight:  failures (strangely, one success in the middle)
  12/10: 8AM completed queue 
  12/10: 3:40PM relaunched with higher details
  Then 7 shows each failing with the error:
      Downloaded file  too small - rescheduling; File sent was `<h2>Server Busy</h2>`

So, that `Server Busy` is the exact text we received when trying to download the video. And that is what we expect when the TiVo internal file server is overloaded, and the model 3 is indeed pretty susceptible to it.  But we try pretty hard to not hit it too fast (e.g. you'll see we wait a whole minute between requests).

Let me just confirm that nothing else is going on at the TiVo simultaneously; especially no other PC is trying to download at the same time, because that would certainly cause the problem.

There's a possibility that one or more of the first shows to fail has glitches causing the file server to fail, so you could try resetting the Tivo, deleting those first failed ones, and retrying the others.
 (ie. Catalyst: Falling in Friendship and other Catalysts maybe too).

Secondly, if that doesn't work, after resetting again, you could try submitting one at a time and see how it goes. Maybe your TiVo needs extra time between downloads and I could give you a version that has that, if the gap seems to help.

So, let me know how those test go.  You can change your log level to Major, that should give all the information I need without overwhelming the log files.

And I promise I'll refrain from any comments as to the adult nature of your shows.

**Comment by davidtkearns** [comment]
Haha the kids love these "adult" shows. 

No other transfers are happening while this is going on. I'll try your suggestions and see how we go. I've done over 50 shows now and this issue is new so maybe picking other shows will help.

**Comment by davidtkearns** [comment]
Programs now transferring fine. Hope all continues to work. Thanks very much for your help.



On 10 December 2015 at 5:08:29 PM, David Kearns (davidtkearns@gmail.com) wrote:

Haha the kids love these "adult" shows. 

No other transfers are happening while this is going on. I'll try your suggestions and see how we go. I've done over 50 shows now and this issue is new so maybe picking other shows will help. 


On 10 Dec 2015, at 4:43 PM, Hugh Mackworth <notifications@github.com> wrote:

So, what you can see there is:
12/9 6PM: some failures and a pause
12/9 7PM; two good transfers
12/9 9:20pm: partial transfers
You'll see a warning message of damaged/incomplete. This is generated when the TiVo tells us it's finished sending the file, but it's not nearly long enough (less than 85% delivered).
12/10 midnight: failures (strangely, one success in the middle)
12/10: 8AM completed queue
12/10: 3:40PM relaunched with higher details
Then 7 shows each failing with the error:
Downloaded file too small - rescheduling; File sent was <h2>Server Busy</h2>

So, that Server Busy is the exact text we received when trying to download the video. And that is what we expect when the TiVo internal file server is overloaded, and the model 3 is indeed pretty susceptible to it. But we try pretty hard to not hit it too fast (e.g. you'll see we wait a whole minute between requests).

Let me just confirm that nothing else is going on at the TiVo simultaneously; especially no other PC is trying to download at the same time, because that would certainly cause the problem.

There's a possibility that one or more of the first shows to fail has glitches causing the file server to fail, so you could try resetting the Tivo, deleting those first failed ones, and retrying the others.
(ie. Catalyst: Falling in Friendship and other Catalysts maybe too).

Secondly, if that doesn't work, after resetting again, you could try submitting one at a time and see how it goes. Maybe your TiVo needs extra time between downloads and I could give you a version that has that, if the gap seems to help.

So, let me know how those test go. You can change your log level to Major, that should give all the information I need without overwhelming the log files.

And I promise I'll refrain from any comments as to the adult nature of your shows.

**Comment by mackworth** [comment]
Glad to hear it. Let me know if there's any problems.
