### ISSUE TITLE
Automatically detecting AC3 5.1 vs stereo? Mencoder vs FFMPEG?

### ISSUE THREAD

**Issue by Mudflapper** [dscottbuch/cTiVo#151]
I have a degree in sound engineering so you'd think I'd be able to figure this out, but no such luck, yet.

I have been using your ProRes LT FFMPEG format to download and save Mov files for editing in Final Cut Pro. It automatically saves the audio as uncompressed PCM with as many channels as exist in the source on the Tivo, which is pretty snazzy. So thank you!

However, many shows that I don't want to edit, I just like to save as MP4 from cTivo. Is there an argument that will auto detect stereo or 5.1 AC3 and copy the audio to the MP4 without reencoding? Will "-oac copy" do the trick for any kind of file with Mencoder?

Followup question: Is there any advantage to using FFMPEG instead of Mencoder?

**Comment by mackworth** [comment]
Historically, the TiVo uses MPEG-2 compression as its internal format. This is incompatible with iTunes and other products and is quite large, so we normally convert to MP4.  If you want the pure file, just use "Decrypted TiVo Show". This will have exactly what we get from the TiVo (after we remove the encryption). It's an MPG file with whatever streams your cable provider gave you.

This may be getting a lot better soon. As the cable industry moves to MP4 as its transmission vehicle, you should be able to do this without any reencoding.  I'm experimenting with it now. 

FFMPeg works great; my understanding is that mencoder uses ffmpeg internally. We use mencoder partly because that's what the original iTivo used to use and we ported their pieces over.
