### ISSUE TITLE
Stray EDL files

### ISSUE THREAD

**Issue by tannebil** [dscottbuch/cTiVo#157]
The iTunes folder is ending up with an .edl file for every episode cTivo adds to iTunes. As best as I can tell, they are comskip files as they seem to be chapter marks. It didn't used to happen but I don't really know when it started happening.

I'm just trashing them all with Hazel so it's not a big problem but thought you'd want to know.

**Comment by mackworth** [comment]
Actually, that was an intentional change, but probably not a good one. When iTunes moves the main file, we notice that and move the SRT, metadata, and EDL files along with it. In retrospect, nothing really uses the EDL other than comskip, so we should probably not move them and just delete it as before.
