### ISSUE TITLE
Just discovered, few questions...

### ISSUE THREAD

**Issue by consumedsoul** [dscottbuch/cTiVo#160]
- How does commercial detection work? Is it basing it on some sort of algorithm or does it look up some sort of existing database? I recall using PyTivo a while back and noticing it wasn't always 100% accurate so concerned.

- If I 'subscribe' to an episode, then will it auto import future episodes (is it based on name of show?) on completion of recording or do I still have to 'schedule' a manual job in the morning etc.?

**Comment by mackworth** [comment]
Commercial detection is based on comskip, and is indeed not 100% accurate. So I prefer to "mark" the commercials instead of "skipping" them. The difference is that marking adds chapter marks at beginning and end of commercials (versus auto-cutting), so when a commercial starts, you hit skip to go to the next segment, but you can still backup if it got it wrong.

That's exactly right (the auto-import part). There's a "series ID" associated with each show, and it remembers which episodes it has downloaded for you, so you should get them automatically.

**Comment by consumedsoul** [comment]
Got it - thanks!

**Comment by mackworth** [comment]
Let me know if you have any questions...
