### ISSUE TITLE
5.1 Audio when using H.264 Medium Quality format

### ISSUE THREAD

**Issue by jimmyhall82** [dscottbuch/cTiVo#179]
Hi, firstly thanks for such a great piece of software. I have been using version 2.4.2 and have been happy with the video results when using the H.264 Medium format, but would really like to export the audio with 5.1 channels, is this possible, and if so, how?

Thanks

**Comment by mackworth** [comment]
First, you should upgrade to 2.4.4. 2.4.2 accidentally broke the auto-update feature, so you're not getting notified.

For your question, there are mencoder commands to create 5.1 sound, but I haven't found how to get it to do the obvious: create stereo if the source has stereo, and create 5.1 if it has 5.1. You can just copy the audio bits through, but then you run into huge sync problems.  

I've been more successful with ffmpeg and have created the attached format. If you want to try it, 
1) Download the [2.5.0 alpha10 version](https://github.com/dscottbuch/cTiVo/releases); you can keep 2.4.4 around, just in case 2.5.0 gives you any problem.
2) Download this file: [ffmpeg.txt](https://github.com/dscottbuch/cTiVo/files/408235/ffmpeg.txt) and rename it to `ffmpeg.plist` (due to GitHub restriction).
3) Use the `File>Import Formats` command and import `ffmpeg.plist` . This will create a format called `FFmpeg default` which converts the video to h.264 without any size change, and converts the audio to ac3 without changing the number of channels. It seems to also convert interlaced to progressive to properly load into iTunes.

 I haven't done a lot of testing, so let me know how it goes for you.   Only restriction is that you can't do commercial skipping with ffmpeg, only commercial marking.
