### ISSUE TITLE
"cTiVo.app is damaged and cannot be opened"

### ISSUE THREAD

**Issue by galacticacic** [dscottbuch/cTiVo#218]
On today's new release my mac reports this is damaged and cannot be opened.

**Comment by mackworth** [comment]
Sigh; always something goes wrong. 

Is this the ctivo.zip or the ctivo10.7.zip?  Which OS are you on? It unzips ok, but then the Finder gives that error?

**Comment by galacticacic** [comment]
This is ctivo.zip. I am on 10.12.2. You are correct in that it unzips and
then finder gives the error when I attempt to open the program. Screenshot
attached.

**Comment by mackworth** [comment]
Thanks. While I'm getting back home, could you try the 10.7 one also?

**Comment by galacticacic** [comment]
I just tried the 10.7. Same response.

**Comment by mackworth** [comment]
So, I double-checked the signing and tried installing it on another Mac here; all looks good.  

Can you go to `System Preferences>Security&Privacy>General` and confirm that you have `Mac App Store and identified developers` enabled (not just `Mac App Store`).  If not, you'll need to change that. 

If so, try rebooting, and confirm you still have a problem. If so, could you set the `Allow apps downloaded from`  to `Anywhere` for the moment and try running it again?

**Comment by galacticacic** [comment]
That seems to have worked. For me I had to run a terminal command (sudo
spctl --master-disable) to restore the "Anywhere" option.

Once that was done and I opened cTivo I recieved the familiar warning about
it being downloaded from the internet, then I was able to open it.

Thank you for your help.

**Comment by mackworth** [comment]
Well, that's still not good. So you had the "identified developers" enabled, and it didn't work?

**Comment by galacticacic** [comment]
Correct. I had to go with "Anywhere" to get it to work.

**Comment by mackworth** [comment]
Well, I really don't understand that. I just had a friend download the new file onto his 10.12.2 system, and he got the expected "This has been downloaded from the internet" with IdentifiedDeveloper, and on the AppStore setting got the expected "can't be opened because it was not downloaded from the App Store."  

Well, I'd recommend putting the setting back now to avoid accidental downloads.

Anyone else run into this; please let me know.  

(@galacticacic, I'll shorten some of the above to make it easier to follow.)

**Comment by mackworth** [comment]
Nobody else seems to be reporting after the full release, so I'll close this for now. Do let me know if anyone sees this issue.
