### ISSUE TITLE
mencorder quit unexpectedly on older processor

### ISSUE THREAD

**Issue by theinvenntor** [dscottbuch/cTiVo#219]
I have used cTivo program for quite some time and thought it great. Now however, I get mencorder quit unexpectedly on every download from my Tivo.

ctivo log shows "Your processor may be too old for mencoder/nYou may need '10.7' version of cTiVo: Possible Problem" Currently and previously I use a mid 2012 2 x 3.06 GHz 6-Core Intel Xeon system in OSX 10.12.3. Not sure but, think this 1st stared with migration to Sierra.

I have uninstalled cTivo completely and have reinstalled latest version 2.5 and get the same error.

Crash report is also attached.
[cTivo Carsh Report.txt](https://github.com/dscottbuch/cTiVo/files/665142/cTivo.Carsh.Report.txt)

**Comment by theinvenntor** [comment]
I download the older 10.7 version and have confirmed that it will download and covert correctly. Hope this helps.

**Comment by mackworth** [comment]
Well, the good news is that's why I put that error msg in. Glad that helped identify the situation.

Mencoder is getting increasingly problematic, and nobody seems to be working on it. In particular, it does not play well with H.264.  If you don't mind, could you try the regular version with ffmpeg and handbrake-based Formats, like Default or HB ones? I'd also like to know if compskip and ccextractor are working with your system. (Should be no problem going back and forth between regular and 10.7, just don't run both  at the same time)

**Comment by mackworth** [comment]
Were you able to try those experiments?
