### ISSUE TITLE
Endless Retries on cTiVo v2.5, macOS 10.11.6

### ISSUE THREAD

**Issue by gfmorris** [dscottbuch/cTiVo#228]
Since the upgrade to v2.5, I have often had issues with endless failures on retries.  [I'm filing this issue upon request after trying the resolution steps from the FAQ](http://ctivo.readthedocs.io/en/latest/wiki/FAQ/#my-shows-arent-downloading-although-i-can-see-the-list-and-can-request-a-download-every-show-tries-several-times-then-gives-up).

- cTiVo 2.5
- El Capitan 10.11.6 (latest)
- iMac 11,1 — 2.8 GHz i7, 16GB RAM
- Files are writing to an external drive, but that connection is solid.
- I can verify the TiVo model and OS number upon request.

The download will work just fine, and cTiVo will step into ad detection.  After that, I get a Failed message.

As an additional data point, my subscriptions have failed to consistently auto-add shows from my TiVo into the queue since these issues began.

These issues are contemporaneous with the 2.4.4 —> 2.5 upgrade, but I can't say for sure that there is an apparent cause/effect relationship.

Please let me know what I can do to help you debug this.  Thanks!

**Comment by mackworth** [comment]
Which Format were you using, but mostly, I need the log. If you can set Debug Level to Major, run a failed attempt and post the log, that'd make it much easier.

**Comment by mackworth** [comment]
Also, you could try the 2.5.1 beta

**Comment by gfmorris** [comment]
Here are Major-evel logs.  I can go to Verbose if needed.  I actually had them at that level but have had an automated process scrubbing logs every week that sent them to the bit farm in the sea.

[com.cTiVo.cTiVo 2017-01-16 21-46.log.txt](https://github.com/dscottbuch/cTiVo/files/709696/com.cTiVo.cTiVo.2017-01-16.21-46.log.txt)

**Comment by mackworth** [comment]
Although I'm not convinced that it's the reason, I'm pretty much done with mencoder (H.264 High Quality, for example). 

Could you try with Format: Default instead? And do it at Detail level (maybe with just one show in queue to keep it simple)

**Comment by gfmorris** [comment]
My first attempt worked!  I've got 17 more to pull — I'll report back when they're all done or if they've failed.

**Comment by mackworth** [comment]
Glad to hear it.  I would like to see a Detail log on the H.264 High Quality one anyways, to figure out why it failed...

**Comment by gfmorris** [comment]
I looked to see if I could force a fetch of H.264 in the queue area (everything pulled across just fine, and so I can reschedule a couple of shows for this), but I can't select H.265 High Quality from the picker in the Format column of the queue listing.  If you can tell me how to do that, I'll give it a shot.

![screen shot 2017-01-17 at 09 03 07](https://cloud.githubusercontent.com/assets/18353537/22025630/cff2baa2-dc93-11e6-8044-2791383e3b31.png)

**Comment by Caesar113** [comment]
I'm having the same issue on macOS 10.12.2 with both 2.5.0 and 2.5.1b3. Updated to macOS 10.12.3b4 today and problems persist. If I add a show to the queue using the Default profile, it will continually fail and retry until it eventually just fails and stops retrying. I have done the usual (e.g. rebooted the TiVo). 2.4.4 still works fine.
[com.cTiVo.cTiVo 2017-01-17 15-28.log.zip](https://github.com/dscottbuch/cTiVo/files/711514/com.cTiVo.cTiVo.2017-01-17.15-28.log.zip)

**Comment by mackworth** [comment]
@gfmorris: cTiVo 2.5 hides the mencoder Formats by default, so just go to Edit>Edit Formats; select the H.264 High Quality  from the pulldown menu, clear the "Hide in User Interface"  box, hit Save and you should be able to use it.

@Caesar113 Your issue is totally different. If you look in the log and search for Fail, you'll see  a StreamErrorCode of 54, which means "the remote server shut down the connection". I've not seen 54 before. Although 49 is common, if you have an anti-virus running, so that'd be my first question. If not, can you try with Decrypted TIVo Show Format instead to confirm whether it's the same without a conversion going on? Third, can you doublecheck that it's still working with 2.4.4, as nothing in that code has really changed much. Finally could you try the following URL in Safari:   http://dvr-e6ba.local.:80/download/The%20Late%20Show%20With%20Stephen%20Colbert.TiVo?Container=%2FNowPlaying&id=25825  (Username: tivo Password: <<YOUR MAK>>)

**Comment by mackworth** [comment]
Any results?

**Comment by gfmorris** [comment]
I tried it with both H.264 High Quality (failed) and then 1080p (also failed) just to see if an exposed-in-user-interface encoding would work.  So we proved that H.264 HQ isn't working (see your frustration/exasperation/last straw with mencoder), but 1080p isn't, either.  Now, I don't know what encoder that uses, but given that v2.5.0 exposes it to the user as a possible format, I did want to test it.

Please let me know if you'd like additional testing with 2.5.0 or further testing with the next version's beta.  I have a large files on my TiVo to try, from 480i to 1080p, and a willingness to test (when not overwhelmed at work, as I have been of late).

**Comment by mackworth** [comment]
So, the 1080p is surprising, but I would like to see the log segments on both that and the H.264 (In Detail debug mode would be best).

**Comment by mackworth** [comment]
@Caesar113 Any luck with those ideas?

**Comment by Caesar113** [comment]
Thanks for responding! With your feedback, I was able to hash this out a bit. It took me a while to figure out, but for some reason my TiVo is now interrupting downloads (both through cTiVo and Safari) quite frequently when operating over WiFi. My router is about 6 feet away from the TiVo and the TiVo shows good signal, and can stream Netflix without issue, so I'm not sure why that is. However, when I plug the TiVo Bolt into Ethernet, downloads complete without issue. This is all very strange, because nothing changed with my home network (I'm a Systems Engineer). I used cTiVo 2.4.4 to download some shows for my iPad before a business trip two weeks ago. Then when I came home last week, I upgraded to 2.5 and this is when I observed the issue started. I found this thread on the forum and with the same basic symptoms, assumed it was related.  I tried reverting back to 2.4.4 and initially had success (as noted in my initial report above), but that was with a short show (e.g. 7 min preview of "next weeks episode") which had failed on 2.5. Longer shows (e.g. anything longer than 10 min) failed on both versions at that point. I Google'd around a bit and I can't seem to find reference to a similar issue. Very strange... I know this is not your problem, but if for some reason you've seen similar issues with a TiVo on WiFi, I'm all ears :) Otherwise, it looks like I'll be running a new Ethernet cable to my entertainment center. Good times!

**Comment by Caesar113** [comment]
Welp... Scratch that! It worked for one day over ethernet. I downloaded 10 hours of content. Today, I'm back to downloads being interrupted in cTiVo and Safari. Same error code 54 in cTiVo. I'm beginning to wonder if the Bolt got a bunk firmware upgrade...

**Comment by mackworth** [comment]
Does streaming work directly to iOS device?  (oddly: hopefully not, because then TiVo tech support might help you; if you mention the Mac in a call, they'll pretty much hang up.)

**Comment by gfmorris** [comment]
@mackworth Let me know what all formats you want tested.  I will be happy to test whatever.

**Comment by mackworth** [comment]
I'd like to get the relevant segments of the log (at Detail-level) on both Default and the H.264 ones.

**Comment by mackworth** [comment]
Hmm?
