### ISSUE TITLE
Incomplete loading of program

### ISSUE THREAD

**Issue by pastorjkeller** [dscottbuch/cTiVo#237]
I have been attempting for a week to transfer a series of 15 episodes from my TiVo to my MacBook. Fourteen of have transferred successfully using the 1080p format. But one episode will not transfer properly. I wondered if the problem was my wifi connection, but I have switched to an ethernet/thunderbolt connection, and it still does not work. Under the 1080p format, 29 minutes of the 1hr 3min show would transfer, but no more. I am using the most recent version of the software.

I have read through posted issues and tried some of the solutions there. For the log I am attaching, Debug Level is set to Detailed, Transport Stream Format is checked on, and I switched to Decrypted TiVo Show. I thought the entire show had transferred -- when I opened the file in QT player, it said the length was 1:03. But now it will not play -- it plays with no audio and a frozen screen for three seconds, and then the app freezes with spinning pinwheel. I have had to force quit three times, and restarted the MacBook for good measure. 

Please let me know what I am missing. The episode plays without any problems on TiVo, so I am at a loss.
[com.cTiVo.cTiVo 2017-02-20 03-11.log.txt](https://github.com/dscottbuch/cTiVo/files/786526/com.cTiVo.cTiVo.2017-02-20.03-11.log.txt)

**Comment by mackworth** [comment]
Well, first, TiVo occasionally has digital glitches in the file where although the file can be viewed just fine, it messes up the encryption process and ceases transmitting part way through. However, cTiVo didn't complain when you downloaded the file without recoding, so that's great news.  To be sure that it wasn't a transmission error before, I'd have to see the logs for that, but my guess is that it's ffmpeg complaining about the file somehow.

Second, raw Transport Stream and QuickTime don't always get along. So I'd try whether VLC can read the file. 

Third, next step I'd do would be to use HB 1080p Format instead of 1080p, and see if that works.

Fourth, you could try and convert the downloaded Decrypted-Format file in Handbrake or ffmpeg manually.

**Comment by pastorjkeller** [comment]
I'm a rookie with this sort of technology, so I had to do a bit of searching to understand all of what you wrote. But I think I get the gist of it...
So I downloaded VLC, and it played the file back without any trouble. It isn't as smooth as QT, but based on what I read, I expected that. 
I'm trying the Mac OS built-in encoding tool to see if that works for creating the MOV file I want so I can edit and dump out the same sort of MP4 file I have for the other episodes.

**Comment by mackworth** [comment]
That's good that VLC can see the file.  So, try the `HB 1080P` Format to see if that works. If it doesn't hit the same glitch, it should create a compatible MP4 version.

If not, then (assuming that the file is an H.264 format) try the Decrypt MP4 before manipulating the MPG you already have.  The Decrypt MP4 Format downloads the file like the Decrypted TiVo does, but puts it into an MP4 container, so we can add the metadata.

**Comment by pastorjkeller** [comment]
HB 1080P did it. That's fantastic. 
If you don't mind educating the ignorant... HB is Handbrake, right? Is it a matter of Handbrake using a different method for creating MP4 files than ffmpeg? 
Thank you!

**Comment by mackworth** [comment]
That is correct. cTiVo's Formats specify which encoder to use and what parameters to give it. If one has a problem reading a specific file, sometimes others can make it through.

Glad it worked!
