### ISSUE TITLE
Incorrect episode number

### ISSUE THREAD

**Issue by mortax** [dscottbuch/cTiVo#251]
I'm seeing the wrong _Episode Number_ for some shows.

the episodes according to cTiVo (four copies of `S03E02`):

![screen shot 2017-06-29 at 2 40 41 pm](https://user-images.githubusercontent.com/788303/27711754-f9bc7376-5cd8-11e7-9662-cbb57f2afd82.png)

according to the TiVo app:

![screen shot 2017-06-29 at 2 42 30 pm](https://user-images.githubusercontent.com/788303/27711828-43138c12-5cd9-11e7-8bdb-4394fa9d2c65.png)
![screen shot 2017-06-29 at 2 42 48 pm](https://user-images.githubusercontent.com/788303/27711833-477e2de8-5cd9-11e7-9b20-732a47a4ec00.png)
![screen shot 2017-06-29 at 2 44 33 pm](https://user-images.githubusercontent.com/788303/27711902-82b4f91e-5cd9-11e7-88bd-4f2e72f55f89.png)

curious if this is a TiVo issue or a cTiVo issue.

**Comment by mackworth** [comment]
That is a TiVo issue, exacerbated when they did the transition to Rovi data.  They deliver different data on their API as they do on the (encrypted) stream. Feel free to raise hell with them, as I've been doing the same.    

Might check if you have "Prefer theTVDB episode Info" checked.  I interrogate their database, and IF we have a good match on episode name and OAD, then it will override the faulty TiVo information.

**Comment by mortax** [comment]
dang. i suspected that was the case - but was afraid to admit it. i'll try `Prefer theTVDB episode Info` and see if that helps.

is there an existing bug/support issue i can reference to add my voice to the choir?

**Comment by mortax** [comment]
enabling that option did not fix my issue. interestingly, theTVDB does have the right data:

![screen shot 2017-06-29 at 3 01 10 pm](https://user-images.githubusercontent.com/788303/27712451-f00f66f0-5cdb-11e7-825e-50e01357baf7.png)

is it possible that the matching against theTVDB could be improved to find cases like this?

**Comment by mackworth** [comment]
Nope. theTVDB specifies that if you have two episodes with the same Original Air Date, it only returns one of them.  

eg. http://thetvdb.com/api/GetEpisodeByAirDate.php?apikey=DB85D57BFFC7DD85&seriesid=272644&airdate=2017-05-19
Thus, all four episodes released that day are mapped to episode 2.

Fortunately, they have a new API that does release all four.

Unfortunately, that requires me to completely rewrite that part of cTIVo :(

**Comment by mortax** [comment]
ah, i see. sigh. maybe i'll have a look and see if i can assist with a PR...

**Comment by mackworth** [comment]
If you like, but as they've announced they're going to migrate in October, I need to port to the new API anyways.  Shouldn't be too hard, as our use is very simple.

**Comment by mortax** [comment]
oh, ok. cool. just let me know if i can help!

**Comment by mackworth** [comment]
So, finally got around to this. Should be a significant improvement in number of shows matched. As expected, it opened a few cans of worms I had sealed away.

Here's a copy (2.6 beta 1 (728) to try. As this is all your fault :), let me know how it goes before I upload it for general use.
https://www.dropbox.com/s/uiik3wy59nq9uqv/cTiVo.zip?dl=0

In particular, I'd love to get validation of new S/E information versus existing 2.5.1 version. (See below for steps)

The Display statistics report has been completely rewritten; let me know if it's understandable.  If there are shows in the list that you think TVDB should have known (e.g. not obscure ones or your local news), then click on the URL to do the lookup manually. As it's a wiki, feel free to add the ones that you think should be there. If you find one that was already there that you think cTiVo should have found, let me know.  Note that the contextual menu (Opt-click) in the Program Table now has the option to force a reload of currently selected shows from TVDB. 

I've also added (for now at least) the ability to edit the Season/Episode information in the drawer. (Double click on a show to open the drawer, then click on Episode Number. Syntax is SxxExx). Keeping this info across reboots and reloads of data fromTVDB is annoying, and opens the door for folks wanting to edit all the TiVo information, which would be a further pain, so it may not survive. But given that TiVo does this particular field wrong, it may be worth keeping.

## Change Log:
Uses TVDB API v2
Rewritten Report on TVDB info
Allows season 0 (Specials in TVDB)
Match TVDB shows with parenthetical years (e.g. The Magicians (2015))
Should match TVDB shows with same episodeName but different Original Air Date
Should match TVDB shows with different episodeName but same Original Air Date
"Reload TVDB Info" in ProgramTable contextual menu 
Edit season/episode entry in drawer

## Bug fixes:
Use .ts for files when appropriate
Fixed TIvos sometimes not getting refreshed during startup.
Add OAD to sorting of Season and NowPlaying (without episodeNames)
"No encoder name" could lead to crash
Remove ContentID experiment
Remove some old code: iTiVo migration and update TiVos
To Restore: Temporarily avoid emptying tivo cache during Empty Cache.

## To validate Season/Episode Info versus version 2.5.1
1) Run 2.5.1.
2) In Advanced Preferences (Cmd-Opt-Comma), empty your cache, quit immediately and re-enter cTivo. To avoid overloading the TiVo or theTVDB, it takes quite a while to re-run the whole lookup, you can monitor in Console or Acitivty Monitor network, or just sort by Episode Number and check if it's still filling in some.
3) In Advanced Preferences, Display statistics, copy and paste the report into TextEdit.  
4) In the main window, sort by Date, Select All. NOTE: It's very important in TextEdit to set the Format>Make Plain Text, or else TextEdit will try and paste the contents of downloaded videos into your document. This will probably either crash your machine or empty your harddrive.) 
5) Now, copy/paste or drag the whole table into TextEdit. 
6) Quit cTivo 2.5.1, and run the beta cTiVo.  
7) Follow same steps 2-5. This time it won't take as long, both because the new TVDB API is faster, but also because I've changed the Empty Cache process temporarily to keep all the TiVo detail information.
8) Compare the two reports and post the results (if you don't mind people seeing your shows).

If you're familiar with Diff, that can help with the compare of the programs (not the statistics). I use Sublime Edit for this as it can compare a window to the contents of a clipboard. Similarly, DON'T drag directly into Sublime, as it will also immediately try and load all the binary video files; cut/paste through a text-format file in TextEdit.

**Comment by mackworth** [comment]
Ah, that version seems to have broken movie downloads.  So don't do any of those with this version.

**Comment by mackworth** [comment]
Any luck?

**Comment by mackworth** [comment]
And now I've finished with the alpha of 3.0 #265 , which now gets the Season/Episode information over Tivo's RPC, which should be identical to the ones shown on your TiVo.  It also uses the above much better matching with TVDB, and you can choose whether to trust TVDB or TiVo for the season episodes.  Major project, but it's much better now.

So this should be all good now!

**Comment by mortax** [comment]
sorry for falling in a hole. I'm mostly back and will try to take a look this weekend!


john

**Comment by mackworth** [comment]
Should be all fixed in alpha4 now.
