### ISSUE TITLE
TS / MPG

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#279]
With the same OS and the same version of CTIVO, machine A downloads ts files for a specific show and machine B downloads an MPG when set to Decrypted TiVo show. I have found no rhyme or reason for it. It is only one specific show that does this.

**Comment by mackworth** [comment]
Most likely Machine A has that channel marked for Transport Stream and Machine B doesn’t. Rather than forcing the user to track the transition by channel, or switching wholesale to TS (which can have other problems), cTiVo has to use heuristics to determine whether a channel has migrated to H.264; notably if we get a file that has no video stream, then it’s probably migrated. So it’s possible that a previous show on Machine A showed that symptom (either because it was H.264, or for some actual error), but the bulk of the shows on that channel are still MPEG2, so Machine B hasn’t seen that symptom.

Easy to check, just go into Edit>Edit Channels on Machine A and see if that particular channel is marked as Needs TS. You can also reset the channel on A back to MPG (or just delete the entry). And it should then revert to MPG (at least until it sees the symptom again).

**Comment by tdlivings** [comment]
Damn right. You really know your stuff! Thank you once again.

**Comment by mackworth** [comment]
You’re welcome!

**Comment by mackworth** [comment]
Just curious; let me know if it switches back soon. Haven’t heard of a case where a channel sends both types of formats.

**Comment by tdlivings** [comment]
Will do, FYI it is OTA, that is why I found that odd.
