### ISSUE TITLE
ctivo suddenly stopped downloading

### ISSUE THREAD

**Issue by desilinguist** [dscottbuch/cTiVo#289]
It was working absolutely fine yesterday and the shows just started failing to download this evening after they were recorded. cTiVo just keeps waiting and failing and waiting and failing. I keep seeing "The request timed out." in the logs. The latest log is attached. Any help would be greatly appreciated!

FYI, I have restarted both the computer as well as the TiVo.

[com.cTiVo.cTiVo 2017-12-08 23-00.log](https://github.com/dscottbuch/cTiVo/files/1544377/com.cTiVo.cTiVo.2017-12-08.23-00.log)

**Comment by mackworth** [comment]
You're also getting "The network connection was lost." Any changes in your network? No antivirus installed?

Can you try this URL in Safari? You'll need `tivo` as the user and your Media Access Key as the password.
http://dvr-0076.local.:80/download/Piya%20Albela.TiVo?Container=%2FNowPlaying&id=180410

**Comment by desilinguist** [comment]
No changes in the network and I haven't installed any antivirus. When I click on that URL and put in the username and password, Safari starts downloading a file but _really_ slowly (like a few hundred bytes/sec) and then finishes and then final final is 19KB (which I am guessing is not the right size?)

Also, overnight, one of the pending transfers actually finished and I see "Complete" indicated for it. The mp4 file is also the right size. However, the others are still pending and keep switching between "Waiting" and "Downloading".

**Comment by mackworth** [comment]
So something is not working right between your Mac and your TiVo. Safari's transferring of your file is seeing the exact same problem.  Agreed, that is not the right size, that show should be 2,254 MB , not 19KB.  It's interesting that it's the same size that gets through on cTiVo as well.  That would lead me to think it's the TiVo rather than the network.

The Waiting/Downloading is because it tries three times to get a file through, and waits 1 minute between tries.  Which is also why you're getting that warning.  If it tries, fails, and then you quit and immediately restart, then you're asking for the next show too soon, and unbelievably, TiVo's file transfer service will crash, meaning you probably need to reboot now.

So definitely restart TiVo. Retry the URL rather than cTiVo as it isolates anything else going on. (but do wait about a minute between tries).

Try that URL from another device (even a phone) and see if you see the same performance.  No other network problems? No streaming trouble on the tivo?

**Comment by desilinguist** [comment]
I just tried streaming from the TiVo to the official iPad app and I didn't have any issues. I tried the URL from another Mac that does not have cTiVo installed and saw the same behavior as before - only 19KB downloaded. I already tried restarting the TiVo yesterday. I will turn it off and on this time.

**Comment by mackworth** [comment]
The streaming is a separate process in TiVo, but that def confirms nothing wrong with your network, just something inside the TiVo. Which generation is it?

If you have a PC, you could try TiVo Desktop, and confirm the transfer fails there. Then TiVo support might be able to help you. If not, you could, ahem, pretend that you do have it. Don’t mention Mac or cTiVo or they won’t help. But you can say that it also fails from the browser.

**Comment by desilinguist** [comment]
I have the TiVo Roamio Pro (Series 5). I don't have a PC but I like your idea :)

What's interesting is that I tried a different show and that started to download and succeeded but yet another different show didn't. Something weird is definitely going on.

**Comment by tdlivings** [comment]
I apologize for chiming in, but, occasionally I get a corrupt show. I can play it from the box but the download fails. Odd I know, but if you skip that show and try the other instances in the queue maybe that will get things going.

**Comment by mackworth** [comment]
Chiming in is good.

You remind me to ask if the corrupted shows are all on one channel. If so, (or even if it's a couple) maybe try forcing "Use TS" on that channel in Edit Channels.

Even easier, try this URL:
http://dvr-0076.local.:80/download/Piya%20Albela.TiVo?Container=%2FNowPlaying&id=180410&Format=video/x-tivo-mpeg-ts

If that works, then try the force TS option.

**Comment by tdlivings** [comment]
It happens once a year. Not even worth trouble shooting

**Comment by desilinguist** [comment]
Turns out all the shows I was trying to transfer were indeed corrupted. They just displayed a black screen when played on the tivo too. Other files transfer fine. Thanks for all the help debugging!
