### ISSUE TITLE
Transfers Failing Because Original Codec Can't Be Detected?

### ISSUE THREAD

**Issue by alkCO** [dscottbuch/cTiVo#294]
For a while now, transfers and re-encodings have failed seemingly at random for reasons I can't quite make out.  It looks like ffmpeg starts to transcode the file, but it gives up saying it can't figure out what video codec was used for the source material.  I've attached a few logs.  I'm hoping someone can help me troubleshoot or give me tips on where to start looking to figure out what is going wrong.

For what it's worth - I did try downloading and decrypting only (using the built-in "Decrypt MP4" format with no transcoding), but that produces a file where VLC says the video stream is MPEG 1/2.  Video doesn't play in VLC, but audio does...

cTiVo 3.0.1 (800) on OS X 10.10.5*

*Yeah, I know.  It's behind a few versions.

[com.cTiVo.cTiVo 2018-01-12 03-30.log](https://github.com/dscottbuch/cTiVo/files/1624947/com.cTiVo.cTiVo.2018-01-12.03-30.log)
[ffmpeg.log](https://github.com/dscottbuch/cTiVo/files/1624948/ffmpeg.log)

**Comment by mackworth** [comment]
Haven't seen anything like that before.  By "at random", you mean that most shows work, but some fail like this? Does the show play ok on the TiVo?  (Sometimes there are digital glitches in the cable transmission; if these are all on the same channel or a small number of channels, you can check those channels' signal strength in your TiVo.)

FYI, Decrypt MP4 is specific to shows already-encoded as MP4, and it looks like this is MPEG2. The comparable one would be Decrypted TiVo Show. That may play in VLC.

You might try the following experiments:
Try decoding with Handbrake-based Format instead; although it uses many of the same libraries, it sometimes has different results.
You're transferring the show as Transport Stream, maybe try Program Stream instead? (This is marked in Edit>Channels, turn off "Use TS" for the channel of this show.)
Finally (and most unlikely), if you have Java installed, you could try using TiVoLibre instead of tivodecode-ng (set in Adv Preferences).

**Comment by alkCO** [comment]
It seems like the program stream vs transport stream was the issue. Thanks for the suggestion! I'm going to mark this as closed. 

I can't recall the original reason why i checked the "always use TS" box in the channels settings, but after unchecking that and letting cTiVo decide, things seem to be back to normal. It might have been a recommendation from the crowd over at tivocommunity.com after getting transfer failures right around the time Comcast started moving to MP4 on some channels in my area. 

I have noticed that Comcast has been screwing around with the channels in my area lately... Go figure.

**Comment by mackworth** [comment]
Great to hear. During my first testing of H.264, I noticed the problem with Transit Stream and MP2 in some cases, which is why I put a lot of effort into detecting and adapting accordingly.
