### ISSUE TITLE
Delete on Tivo after download complete?

### ISSUE THREAD

**Issue by bradbamford** [dscottbuch/cTiVo#296]
Is it possible to add a preference option to **Delete from Tivo after successful download** ?
Currently, I right click each file after download and click Delete from Tivo.
It would be nice if this was automatic.

**Comment by mackworth** [comment]
Great idea; shouldn't be hard to implement.  

But I'd love to hear from anyone else who would use it?

**Comment by bradbamford** [comment]
I'll add another benefit:

There are many shows and movies that have the dreaded copyright and cannot be downloaded via cTiVo. Often times these (and others) are auto deleted due to space restraints before I have time to notice and watch them. 

I just came back from a 2 week vacation, I know I lost movies that recorded but I wasn't here to watch (or download) before TiVo reclaimed the space. 
This feature would have been nice because instead, I returned to a TiVo 100% full with mostly episodes already backed up by cTiVo. Others were truncated before I had a chance to download.

**Comment by jridder** [comment]
I would love it. 

LOL, while you are at it can you add the option on how many encoders can run at once? I have a heck of a time getting the option to stick.

**Comment by mackworth** [comment]
Meaning that you've set it in Terminal, but it resets itself??

Actually planning on adding this as a Terminal option for now, and see if folks want it in the UI.

**Comment by jridder** [comment]
Correct. I have set it and confirmed the setting is there and then launched cTivo and the option disappeared.

**Comment by mackworth** [comment]
So I verified there's nothing in cTiVo that ever changes that setting, and it does work on my system.

Just checking: you set it with `defaults write com.ctivo.ctivo MaxNumberEncoders 1` and confirmed it with `defaults read com.ctivo.ctivo MaxNumberEncoders` rather than with a text editor on the plist? And then after the launch, `defaults read` again says "does not exist"? Or it just doesn't work?

I do know there's a vulnerable period immediately after it quits, during which it overwrites the plist on disk. Maybe try waiting a little while before defaults write?

**Comment by jridder** [comment]
Correct, I followed the defaults write/defaults read process. Was able to even see it present in the plist at one point. After trying a few times it appears to finally stuck. 
I am wondering if I was within that window after a quit.

**Comment by mackworth** [comment]
So, I decided that both of these merited a UI, and are in 3.1.1 beta2.  Let me know if they work for you.
