### ISSUE TITLE
comskip with decode mp4 not working

### ISSUE THREAD

**Issue by sfenwick** [dscottbuch/cTiVo#302]
I've got "Mark Commercials" checked, and comskip installed in /usr/local/bin, but commercials don't seem to be getting marked; at least they don't show up in VLC as bookmarks. I don't see any record of comskip being invoked in the cTivo logs.

**Comment by mackworth** [comment]
We include the comskip binary in ctivo, so that shouldn't be necessary  (nor cause any problem). 
At "Normal" logging, we don't show individual steps unless there's a problem.
Try increasing to "Major", and you should see "Starting task commercial" in the logs. If you increase to Detail, it'll show the command line invocation.
With Decrypt MP4, as encoding is trivial, you should see a long period of Detecting commercials in the progress bar of the download in the UI.
If it's still not working, post a Detail log, and let's see what's wrong.

**Comment by sfenwick** [comment]
I think I'll declare pilot error on this one. Seems to be work at a basic level now, tuning needed (but that seems to be a thread with comskip). Thanks!

**Comment by mackworth** [comment]
Good to hear...I guess!
