### ISSUE TITLE
Command + c no longer copies

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#312]
Just a heads up. Command c no longer copies selected . The right click copy works though. Thank you for your efforts.

**Comment by mackworth** [comment]
Hmm, my copy seems to be working fine, both Cmd-C and Edit>Copy. Can you give more details?

And ... not sure what you mean by right-click copy, AFAIK, it doesn't have a command like that?

**Comment by tdlivings** [comment]
Mouse right click submenu > copy 

Command +C keyboard copies but doesn’t past into metadata description. I see it works into a note or other text based sheet. I am thinking it might be related to where Ia am copying it into. I will start using the right click submenu. Thanks for your help and quick response.

**Comment by mackworth** [comment]
So, FYI, we put two types of info on the clipboard when you copy:
one is a "Show", which is only used to paste into the Download or Subscription; this is how drag/drop works.

Second is the text description, and the third is a fileURL (if you've downloaded the show), which allows you to drag into the Finder. 
One problem to note is that there's an bug/issue with TextEdit, where if you have a Rich text format, it tries to paste the entire show (all xGB of it) as text in the document.

I'm still not seeing the copy command in the contextual menu in the table. Can you send me a screen capture like this one?
<img width="150" alt="screen shot 2018-03-08 at 10 15 29 am" src="https://user-images.githubusercontent.com/117963/37168421-b18dc83c-22b9-11e8-8962-91a841e8e2c0.png">

Oh, ... are we talking about in the drawer (the side box that has detail of a specific show)?   There is a copy command there when you have text selected, which seems to work from both the right-click and the main menu.  It does not have the ability to edit in general (e.g. paste) with the exception of season/episode due to the historic problems there.

**Comment by tdlivings** [comment]
Yes pop out then description. But no worries. I can use right click. I am just a fan of keyboard shortcuts.
