### ISSUE TITLE
Download fails in Yosemite

### ISSUE THREAD

**Issue by jimtaylor61** [dscottbuch/cTiVo#70]

**Comment by Sologeoff** [comment]
Hi to the learned ones I am newbie
I have just purchased a macbook pro with yosemite (I live in Australia)
ctivo recognizes my tivo & shows all of my saved tivo programs.
BUT it won't download any programs from my tivo it fails constantly
Hope somebody can help
Kind Regards
Geoff

**Comment by mackworth** [comment]
Hi, unfortunately, we've had a lot of issues in Australia. For some reason, only in Australia, TiVo converted a few years ago to support a different stream format (called Transport Stream versus Progressive Stream), and it's meant that file transfers became very problematic. 

I'm afraid I can't offer much hope as it does seem TiVo has given up on that market now. If you get in touch with TiVo support, ask them if your TiVo Desktop on your "PC" will work (don't mention the even more unsupported Mac.)

**Comment by mackworth** [comment]
@Sologeoff On second thought, I have a possible fix.  Here's an [experimental version](https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip); it's available here if you'd like to give it a try. Let me know if it works...

**Comment by Sologeoff** [comment]
Hi Hugh
Thank you for your prompt reply & info to help, unfortunatley the same result I downloaded the experimental version & installed but to no avail still refuses to download the file from the tivo.
But I must say at least this version gave me a glimmer of hope & it stated it was downloading the file at 50mps  but then failed  
I will try the hard way with KMTTG
I did have success with KMTTG under Linux so I am hopeful I can get it working under the mac book pro yosemite
Kind Regards
Geoff

**Comment by mackworth** [comment]
Can you set the logging to Detail (in Prefs) and then post the result (has to be somewhere else like DropBox as GitHub won't accept files)?

**Comment by Sologeoff** [comment]
Hi Hugh I didn’t understand how to do your last request to try and help me.
So I have made a PDF ctivo log.
Hope this helps to help me?
Regards
Geoff

**Comment by mackworth** [comment]
The text version is fine, it's just that github won't let you post anything like that, and strips them from emails. So if you have a Dropbox account, just put it in Public folder, and right click to get the sharing URL, then paste that URL here.

**Comment by Sologeoff** [comment]
Hi Hugh

As requested the Dropbox URL’s  below

https://dl.dropboxusercontent.com/u/7638125/IMG_0367.JPG <https://dl.dropboxusercontent.com/u/7638125/IMG_0367.JPG>

https://dl.dropboxusercontent.com/u/7638125/CTivo%20log.pdf <https://dl.dropboxusercontent.com/u/7638125/CTivo%20log.pdf>

Hope this helps to help me
Kind Regards
Geoff

**Comment by mackworth** [comment]
Hi, Geoff.  So, what that tells me is every time you ask the TiVo for a file it says "Server busy". This is very common, and it means that the server inside the TiVo has crashed. Now, it may also mean that it didn't like the way we asked for the file.  

So one step is to restart the TiVo and see if you still get an error.

If you do, then the second step is to try the following line in Safari (or whatever browser you use).

Assuming that gives you a list of shows, click on this link:
https://dvr-fb17.local./nowplaying/index.html  

That should give you a list of shows. Right click on one of the links that says "Download MPEG-TS" and give me the result; same for the "Download MPEG-PS". Finally click on the -TS one and see if it starts downloading the file (No need to let it completely download, just a few hundred K to make sure its really going.) Let me know if that worked.

**Comment by Sologeoff** [comment]
Hi Hugh
I unplugged the tivo restarted as requested
Still the same error
https://dl.dropboxusercontent.com/u/7638125/Terminal%20Saved%20Output <https://dl.dropboxusercontent.com/u/7638125/Terminal%20Saved%20Output>

step 2
I actioned the URL link you supplied
https://dl.dropboxusercontent.com/u/7638125/dvr-fb17.local..webarchive <https://dl.dropboxusercontent.com/u/7638125/dvr-fb17.local..webarchive>

I right clicked on the files
https://dl.dropboxusercontent.com/u/7638125/Right%20click%20on%20MPEG-TS%20and%20MPEG_PS.rtf <https://dl.dropboxusercontent.com/u/7638125/Right%20click%20on%20MPEG-TS%20and%20MPEG_PS.rtf>
https://dl.dropboxusercontent.com/u/7638125/dvr-fb17.local..2webarchive <https://dl.dropboxusercontent.com/u/7638125/dvr-fb17.local..2webarchive>

Can you try on your box my MEDIA key is 5665764791 (IT is given in trust not to be shared.)
My Tivo URL is 192.168.0.5
Kind Regards
Geoff

**Comment by mackworth** [comment]
So, you're getting the same error from the UI as cTiVo is.  Do you get the same error msg (Server Busy) on both the -TS and the -PS  links?  

So, I'm surprised that KMTTG works for you, given this. First, you don't seem to be getting any files downloaded here at all, and second that they can handle the PS format (other than in Windows, where they access TiVo's DLL).  If you can get it to download a file, then let me know what URL they are using.

**Comment by Sologeoff** [comment]
Hi Hugh
In KMTTG it gives this error
> java.io.IOException: Server returned HTTP response code: 503 for URL: Error <http://stackoverflow.com/questions/21447862/java-io-ioexception-server-returned-http-response-code-503-for-url-error>
> A 503 is usually caused by a temporary overloading of the web server. (So I am told)
If that is so, why is it so?
Regards
Geoff

**Comment by mackworth** [comment]
That's basically the same msg (Server Busy). So as suspected, that's not currently getting files out of the TiVo either. (BTW, have you checked your TiVo service page to ensure downloads are enabled; the US version of the site is here: https://www.tivo.com/tivo-mma/login/show.do  )

**Comment by Sologeoff** [comment]
Hi Hugh
Success!!!
I turned off Tivo disconnected network & cable modem restarted tivo without network, I assumed it has flushed out the cache
CTivo still fails 
but I can download via Safari and then convert the ts file to my needs.
the long way around
KMTTG fails as well
How do we make sense of all this?
CTivo fails
KMTTG fails
Via the web browser is okay?
Thank you for your prompt response & service it is appreciated.
Kind Regards
Geoff

**Comment by mackworth** [comment]
Which version of cTiVo are you trying? Do About cTiVo and check that it's version 534. 

Then let me know exactly what the web browser URL is (and if it was the TS, try the PS as well in the browser, or vice-versa and let me know what that URL is and whether it worked.)

**Comment by freduruncle** [comment]
I've been using 2.4.0b7 on my ancient Macbook Pro running OS X 10.7.5 with no issues but since its just a Core 2 Duo its painfully slow.  I put the same version on my Mac Pro running Yosemite and it fails to download ANYTHING at all.  It tries and tries (I upped the attempts in the Advanced Settings tab) and finally gives up.  Its on the same network/router etc. as the older OS but just fails continually.  I've tried restarting the Tivo HD, deleting the plist and restarting the cache etc. as described in this thread but no go.  I'd really like to get this running since the encoding would be so much faster and I could use local drives with more space available.  Any chance any of the older versions would work any better with Yosemite?

Thanks...

**Comment by mackworth** [comment]
Happy to help; if you can set debug to Detail and post the log somewhere with a pointer here, that'd be the best start.  There is still a major bug with Yosemite which affects some people, and is driving me nuts (especially as I can't trigger it  on my machine), but the symptom you're describing is NOT one of them.

**Comment by freduruncle** [comment]
Thanks for the offer.  I cut the download attempts down to 3 and reran a download attempt.  Here is the zipped log file.  Its sitting on a cloud site that's going away in a few weeks but should be ok for now.

http://ppl.ug/WVfhzygULYc/

**Comment by mackworth** [comment]
So, I'm seeing the Tivo not respond at all to download requests.  Can you click on the following URL in your browser (and provide username: "tivo" password: your MAK )?  It should start downloading.  Also, have you checked if it's still working on your older Mac?

http://dvr-e379.local.:80/download/Andrea%20Mitchell%20Reports.TiVo?Container=%2FNowPlaying&id=8404028

As an aside, I see you're using the filename template. As the sample shows, you might want to change it from `[MainTitle] - [SeriesEpNumber] - [EpisodeTitle]`  to `[MainTitle][" - " SeriesEpNumber ][" - EpisodeTitle]` which will only add the hyphens if those fields exist.

**Comment by freduruncle** [comment]
1.  Yes, it starts downloading and bits are being moved to my Mac.
2.  I had this problem when I first tried cTivo on my Mac so I put it on the Macbook and it worked.  Its been happily downloading and processing shows for about a week now with no problems at all.  I turned it off this morning so it wouldn't interfere with my attempts on this machine.  As of 6 pm yesterday it continued to work fine.  The Mac didn't work a week ago and still doesn't work.

Thanks for the formatting tip.  I just turned that on but haven't processed a file since I did it.

**Comment by mackworth** [comment]
Ok, this is very strange. I've never seen it download from the browser and not from cTiVo.  Can you triple-check the MAK in cTiVo (Edit>Edit Tivo) and if ok, go into Keychain Access and delete any tivo MAKs stored there (but not xxx.tivo.com or Tivo Broadcast Center).   

You don't have happen to have ctivo set up for remote access, do you?

**Comment by freduruncle** [comment]
I quadruple checked the MAK and both machines match and match the one I had written down to do that browser download so I'm pretty sure all is OK there.

If by remote access you mean adding "Remote (Manual) TiVo's" then no.  I haven't touched that window.

I went into Keychain Access and I can't find any reference to TiVo at all except for some entries put there by 1Password.  Can you tell me more specifically where to look in Keychain Access?  I'm a long time Mac user but never had the need to more than glance at the KA app.

**Comment by mackworth** [comment]
This is very odd indeed. We're launching the proper URL, and that URL works in two other apps, but not this one. One thing occurred to me last night; can you go to System Preferences>Security>Firewall>Firewall Options? Which settings are on?

I'm just finishing a new beta, which will have a little more logging here, so if the firewall doesn't explain it, then maybe there's an authentication issue.

**Comment by freduruncle** [comment]
The firewall has given me problems with other software over the years so I’ve long since turned it off.  Basically, the firewall is turned off and all advanced preferences on that pane or default and not messed with.




My old laptop keeps chugging along happily with this version of cTiVo so I an afford to be patient.  I’m a retired engineer with time on my hands so if I can try anything at all, I’m willing just out of curiosity!





—
WTG

**Comment by freduruncle** [comment]
These two error pairs show up for each failed download attempt.  

5/18/15 1:34:45.123 PM cTiVo[11521]: tcp_connection_destination_prepare_complete 7 connectx to 192.168.1.129:80@en0 failed: Can't assign requested address
5/18/15 1:34:45.123 PM cTiVo[11521]: tcp_connection_destination_prepare_complete 7 connectx to 192.168.1.129:80@en2 failed: Can't assign requested address

Obviously, the IP is the only assigned by the router to the TiVo.

**Comment by mackworth** [comment]
ok, so it looks like you have two network connections to your TiVo. Maybe Ethernet and WiFi?  If that's accurate, maybe try disconnecting one.  And this is after rebooting?

**Comment by freduruncle** [comment]
Yes and Yes.  I noticed I had the WiFi turned on and since this is a desktop machine, I didn't need it.  I turned it off now.  I'm not sure if the above was before or after that.  I recently rebooted the machine but not since turning off the Wi-Fi.  I'll do that soon and let you know....

**Comment by mackworth** [comment]
Oh, another experiment to try. Create a Manual TiVo  (in Edit>Edit TiVos) with IP address of 192.168.1.129, the default 80/443 ports and your MAK. Then turn off the Enabled field on the Local Network one, and see if you can download from this one.

**Comment by freduruncle** [comment]
Ok.  Will do.  In the mean time, I rebooted with Wi-Fi off, started cTiVo and watched the console for cTiVo references.  This mean anything to you?  Each line was labelled as cTiVo but doesn't seem relevant to me...

5/18/15 4:02:22.167 PM cTiVo[2975]: Error loading /Library/ScriptingAdditions/XMail.osax/Contents/MacOS/XMail:  dlopen(/Library/ScriptingAdditions/XMail.osax/Contents/MacOS/XMail, 262): no suitable image found.  Did find:
	/Library/ScriptingAdditions/XMail.osax/Contents/MacOS/XMail: no matching architecture in universal wrapper
5/18/15 4:02:22.169 PM cTiVo[2975]: Error loading /Users/goose/Library/ScriptingAdditions/YouHelper.osax/Contents/MacOS/YouHelper:  dlopen(/Users/goose/Library/ScriptingAdditions/YouHelper.osax/Contents/MacOS/YouHelper, 262): no suitable image found.  Did find:
	/Users/goose/Library/ScriptingAdditions/YouHelper.osax/Contents/MacOS/YouHelper: no matching architecture in universal wrapper

**Comment by freduruncle** [comment]
Yes!  The manual TiVo immediately took off downloading with the xfer rate and Estimated Time Left displayed.  Not sure what the problem was but this seems to work find though I've not, of course fully finished the load yet.....

Thank you!

**Comment by mackworth** [comment]
Excellent! So that tells us it's a local DNS problem.  There's a known Apple problem where the DNS process, discovered, gets damaged. See http://arstechnica.com/apple/2015/01/why-dns-in-os-x-10-10-is-broken-and-what-you-can-do-to-fix-it/ 

 If I were you, I would do a very annoying process that I just completed in my own net, and it helped.  Turn everything using the Internet off (routers, cable modem, computers, cell phones, tablets, Apple TV, TiVo, etc), then after they are all off,  turn them back on from the Internet back to the core.  This resets all the local copies, and they then chat among themselves to reestablish the directory.

Then you should disable the manual TiVo entry and re-enable the local net one. See if it works, and let me know.

**Comment by freduruncle** [comment]
Now that you mention it, I heard about that on one of the TWIT podcasts (or maybe on the DTNS podcast).  Its one of those things you hear but don't understand the effect it might have on you.  I'll hopefully get time to try that tomorrow.  I have a LOT of devices going and the process will be painful :)

Yes, and kmttg too.  I'm afraid I know just enough to be dangerous here :)  I'll let you know what happens.... and thanks for sticking with me here.....

**Comment by freduruncle** [comment]
Apologies for this being a little off topic but it involves the machine we have been exploring and perhaps a beta bug?.  In the manual mode today it successfully totally processed a download of a subscribed show using the AppleTV format.  It said COMPLETE so I deleted it from the queue and forgot about it.  I left cTiVo running in the background.  A few hours later I happened to have the activity monitor open and the mencoder process was still hovering about 350% CPU usage even though nothing was happening in cTiVo.  I quit cTiVo and it went away. Restarting cTiVo was as expected.  No mencoder process.  Am I missing something or is there a bug of some sort here?  I don't expect a long discussion here but since we're talking beta version I thought I should at least mention it.....

**Comment by mackworth** [comment]
Nope, haven't seen anything like that.  Let me know if it happens again.  

Btw, for some reason comskip explicitly ignores the first little bit of the show, so, yes, if you recorded a minute earlier, that should work.  You can also use MPEG Streamclip (http://www.squared5.com/ ) , it will cut files as you wish with no recoding (just copying the file)

**Comment by freduruncle** [comment]
Thanks for the tip.  I'll give it a try.  I'll also keep an eye on that lingering mencoder thing and see if it happens again.

**Comment by freduruncle** [comment]
Stream clip works well.  Thanks.

I've not had time to do that DNS purge but I have run into additional Yosemite issues and was wondering if its the problem you're chasing at the moment.  Some shows like my 85 year old mother's soaps process just fine every time.  Other shows seem to fail at various places and the queue starts all over again.  The last one I noticed made it though 95% of the com skip and then just restarted the download again.  Others seem to hang in download.  Meanwhile, the old laptop running OS X 10.7.5 just works every time.   Do these Yosemite symptoms mean anything to you?

**Comment by mackworth** [comment]
When you say "the queue starts all over", do you mean that particular show re-downloads, or something more dramatic?  Mostly, the Yosemite symptoms seem to be related to starting up, rather than during the process. Certainly if you have a show that fails repeatedly and can be accessed by the older one, I'd love to know about that. But if's just the first time?  comskip in particular is notoriously unreliable.

**Comment by freduruncle** [comment]
Yes, I have a show that failed 3-4 times (died at some point and then re-started the download on the Yosemite machine and worked just fine the first time on the older machine.  I still have that file on my TiVo.  I'll try it alone over the weekend and make sure I'm not misleading you here.  I'm not really watching too closely lately since I'm just in beta test mode and not really doing shows I want to keep or anything.  I'll post what I find here when I can be "certain."

**Comment by freduruncle** [comment]
Looks like your assessment was correct.  The show that failed to complete com skip and encoding multiple times the other day completed the first time today.  I'll keep my eyes open for other weird Yosemite cases but it appears my comments above were just a red herring.  Sorry about that.

**Comment by mackworth** [comment]
No problem  Good to hear about any issues, repeatable or not!
