### ISSUE TITLE
Subscribed shows not getting queued

### ISSUE THREAD

**Issue by mggpatt** [dscottbuch/cTiVo#72]
Subscribed shows will show up in the top list as being available but have no checkmark as being queued up and do not get transferred.

**Comment by mggpatt** [comment]
Hi!
I apologize if that is not the appropriate way to ask you questions about cTiVo but I just can't figure out how to do it through that GitHub site.  :- (
I am having problems with the error code "Failed" on many of my programs.
I would just like to do a total UNinstall including all preferences and reinstall.
Can you please tell me how to do the UNinstall part?
Thanks so much. Really a great program.
Greg

**Comment by mackworth** [comment]
No problem. There's really only two files: the application and the preference file. The preferences and queue are stored in ~/Library/Preferences/cTivo.cTivo.plist .  Note that since Mavericks, after deleting a preference file for any program, you have to then reboot or log out to completely remove it (it keeps a copy in memory).

There's also files in /tmp/ctivo and /tmp/ctivo_details, In addition to manually deleting these (while the program isn't running), the first directory should be emptied every time you start the program, and the second can be emptied in Advanced Preferences.

But resetting is unlikely to fix your problem. I suggest you set the Debug level to Major in Preferences, run some shows that fail and then post the log somewhere with a pointer. I should be able to quickly figure out what's wrong.

**Comment by mggpatt** [comment]
Thanks Hugh....You were talking a little Geek there but that is about how much of it I speak. I will call up your other emails instructing me how to do that logging thing and try to get it up for you to look at.
What site do I start a new thread?
Thanks for your help.
Greg

**Comment by mackworth** [comment]
Sorry, I had you confused with another person I was helping; they were brand new to the program.  

First, if you click on the "view it on GitHub" button at the bottom of this email, you'll see that these emails are collected as a thread there. (Therefore, best not to include the previous text). Perfectly fine way to interact; no need for a new thread. In this particular case, somehow vtrandal got mixed into your thread (when you do want to create a new thread, just go to github/com/dscottbuch/cTiVo)

Second, looking back, originally you were reporting a problem with subscriptions, is that one ok now?

Third, yes, if you follow the logging instructions above, that'll give me the info I need to follow up. The key takeaway from my geeky uninstall instructions is "uninstalling is unlikely to fix a Failed problem".
