### ISSUE TITLE
cTivo queue never comes out of "PAUSED" state

### ISSUE THREAD

**Issue by xxKeoxx** [dscottbuch/cTiVo#88]
I can get my shows to download, but once they are all downloaded my cTivo goes into a paused state.  After that it never comes out of that state unless I go into the menu and tell it to resume.  Is cTivo supposed to "RESUME" when a new show is found?  If so, how do I enable that?

**Comment by mackworth** [comment]
I need a little more detail to answer properly. I assume by "paused" you mean that nothing visibly happens, rather than a big red "Paused" sign appearing. (The latter is when you turn off the queue processing, either manually in the File menu, or with the scheduling option in Preferences.)  I also assume that you have created a subscription that should be triggered when a new matching show appears, but isn't. (Or are you looking to record all shows? It can do that to, but it has to be set up.)

By default, to avoid hitting your TiVo too hard, cTiVo will wait 15 minutes to refresh the NowPlaying list; (you can change this time in Adv Preferences, or you can do it manually with File>Refresh (Cmd-R)). After it refreshes, if you have a relevant subscription, it should indeed automatically create a download entry, and (if the queue is processing) should immediately start that download (maybe with a 1 minute delay).

So, let me know which path isn't working for you!

**Comment by xxKeoxx** [comment]
I am referring to the red "Paused" inside the Queue window.  Right now I don't have any new episodes to test it on, but the last few times my Tivo Roamio had new recordings and 2 days later cTivo still hadn't copied them down.  I had to go into the menu and select "Resume Queue".  Once I did that it started the download.

**Comment by mackworth** [comment]
So, if that's visible, cTiVo will definitely not proceed. It should only show up if (a) you do File>Pause Queue (or type Cmd-U) or (b) you have Scheduling Active in Preferences. If it's (b) though, it should turn itself on during the range of hours indicated on that screen.  

Let me know if you're seeing it show up without having either of those things.

**Comment by xxKeoxx** [comment]
Ok.  That makes sense.  I have scheduling turned on between 01:00 and 06:00.  Any idea how I can figure out why my recordings didn't download during that window?

**Comment by mackworth** [comment]
Probably because your system was asleep then. We can prevent sleep during queue processing, but we can't schedule a wakeup time; you have to do that in Sys Pref>Energy Saver>Schedule.
