### ISSUE TITLE
Download being cut short

### ISSUE THREAD

**Issue by ramatsu** [dscottbuch/cTiVo#90]
Trying to download the 3-hour NFC Championship game, I consistently get the first 26 minutes only. Status reports that it's complete:

![image](https://cloud.githubusercontent.com/assets/1444745/5859898/aadd9196-a212-11e4-8f55-838f44e9dfe9.png)

I've tried this with at least 3 different codecs, including Decrypted Tivo, High Quality H264, and HandBrake AppleTV.

I also downloaded a 30-minute and a 1-hour show that followed the game, successfully.

cTiVo 3.2.1
Yosemite 10.10.1
Retina MBP 15" 16GB/500GB

Couldn't find anything about this issue elsewhere.

**Comment by mackworth** [comment]
This is probably due to a digital glitch in the transmission, which doesn't affect playback much, but causes the MAK-encryption in the download process to fail. (If you watch the game at just the point where the download fails, you may see a momentary glitch.) Unfortunately, the TiVo also mistakenly reports that the download has successfully completed. We monitor for this combination and report if the downloaded file is less than 85% of the original size (there is some normal fluctuation that occurs), so given the 1/6th download, you should have gotten a notification "Warning: Show may be damaged/incomplete", although that is in addition to the show downloaded, so depending on how your notifications are set up you may miss that one.

If you want to confirm this, you can connect via the browser and download the file (in other words, bypassing cTiVo entirely). Given the symptom you've described. it'll stop at the same point.

Let me just add my condolences to hear that it happened on an important program!

**Comment by ramatsu** [comment]
Just checked and sure enough, there's the slightest of hiccups at that point. Argh! 

I came back here to change this into a bug about overcoming the digital glitch issue, but it sounds like that's a pretty well established dead end out of the hands of cTiVo if the TiVo just won't send anything after that.
