### ISSUE TITLE
1 show fails to download

### ISSUE THREAD

**Issue by mrfusiontm** [dscottbuch/cTiVo#99]
Here's a verbose log from a failed attempt to download "The Flash" from my TiVo.
It seems to download other shows just fine, but not this particular episode.  I viewed the episode in
question on the TiVo and the content seems fine. 

https://drive.bitcasa.com/send/ixijNJB1s8SeYvMwu9vhWvHsn71b4Rt6tLQjgVrECL6-

I'm on the latest Yosemite patches and using the latest beta of cTiVo

**Comment by mackworth** [comment]
Hi, I apologize; I don't think I ever saw this one.  In looking at your logs I see:

> 2015-03-28 09:19:20:981 MTTask>saveLogFileType:fromPath:@ 135>errFile for task decrypt: Encryption by QUALCOMM ;)
>  29295: stream_no: bd, block_no: 1
>Creating turing stream for packet type bd
 >...
>Invalid MAK -- aborting
>processing frame: Undefined error: 0
>2015-03-28 09:19:20:981 MTDownload>saveCurrentLogFiles@155>The Flash: Rogue Time (FamilyRoom TiVo) downloaded 557190 of 6354370560.000000 bytes; 0%

The Invalid MAK error from tivoDecode means that the decryption failed. If this occurred in other shows and at the beginning of the file, then it probably is due to having the wrong MAK. Here it simply means that the data being decrypted was corrupted. Unfortunately, tivoDecode doesn't give anyway to ignore the error and proceed. We see this occasionally, sometimes the symptom is that the tivo just stops downloading, sometimes we get this error. The show may have a glitch on the screen and yet continue, but it can't be downloaded.

**Comment by mrfusiontm** [comment]
Ok, but now I've got three episodes that fail to download (all of them The Flash).  It seems odd that this is the only show that is having this problem.  I cleared out the logs and started a new one where I tried to download these three problem episodes.

https://drive.bitcasa.com/send/p-bvWyD67kaX38LWbsnGp0ORdG2tu08J_cCODUNT5UxM

I found the "invalid MAK" that caused the problem with the first one I sent, but did not find that for the other two.

**Comment by mackworth** [comment]
The others (Grodd Lives and Rogue Air) show download failures (see below).  The first one fails at 41% of the way through, but the rest fail at 0%. The first one looks like a network problem, as we were told:

> 2015-05-14 07:01:57:728 MTTiVo>tivoNetworkCallback@ 182>Tivo FamilyRoom TiVo is now online
> 2015-05-14 07:01:57:728 MTMainWindowController>networkChanged:@ 130>MainWindow network Changed
 
and then a minute later, it timed out.

> 2015-05-14 07:02:55:684 MTDownload>connection:didFailWithError:@ 2185>URL Connection Failed with error Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo=0x6080000ef400 {NSUnderlyingError=0x60800064f510 "The request timed out.", NSErrorFailingURLStringKey=http://dvr-5d49.local.:80/download/The%20Flash.TiVo?Container=%2FNowPlaying&id=10639908, NSErrorFailingURLKey=http://dvr-5d49.local.:80/download/The%20Flash.TiVo?Container=%2FNowPlaying&id=10639908, NSLocalizedDescription=The request timed out.}
> 2015-05-14 07:02:55:684 MTDownload>saveCurrentLogFiles@155>The Flash: Grodd Lives (FamilyRoom TiVo) downloaded 2603868498 of 6333399040.000000 bytes; 41%

But then the retries didn't get any data at all:

> 2015-05-14 07:04:57:388 MTDownload>saveCurrentLogFiles@155>The Flash: Grodd Lives (FamilyRoom TiVo) downloaded 0 of 6333399040.000000 bytes; 0%
> 2015-05-14 07:06:57:615 MTDownload>saveCurrentLogFiles@155>The Flash: Grodd Lives (FamilyRoom TiVo) downloaded 0 of 6333399040.000000 bytes; 0%
> 2015-05-14 07:08:58:957 MTDownload>saveCurrentLogFiles@155>The Flash: Grodd Lives (FamilyRoom TiVo) downloaded 0 of 6333399040.000000 bytes; 0%
> 2015-05-14 07:11:00:362 MTDownload>saveCurrentLogFiles@155>The Flash: Rogue Air (FamilyRoom TiVo) downloaded 0 of 6742343680.000000 bytes; 0%
> 2015-05-14 07:13:03:221 MTDownload>saveCurrentLogFiles@155>The Flash: Rogue Air (FamilyRoom TiVo) downloaded 0 of 6742343680.000000 bytes; 0%
> 2015-05-14 07:15:06:405 MTDownload>saveCurrentLogFiles@155>The Flash: Rogue Air (FamilyRoom TiVo) downloaded 0 of 6742343680.000000 bytes; 0%
> 2015-05-14 07:17:13:510 MTDownload>saveCurrentLogFiles@155>The Flash: Rogue Air (FamilyRoom TiVo) downloaded 0 of 6742343680.000000 bytes; 0%
 
Looks to me like the download process got messed up due to some network problem. Personally, I'd reboot the TiVo and try those last two again.  If it still doesn't work, try this URL in your browser:

http://dvr-5d49.local.:80/download/The%20Flash.TiVo?Container=%2FNowPlaying&id=10639908

If that doesn't work, then there's clearly something wrong with downloading that particular show. If it does work, then there's something wrong with cTiVo and I'm happy to help figure it out.

**Comment by mrfusiontm** [comment]
Thanks I'll give that stuff a try and let you know what happens

**Comment by mrfusiontm** [comment]
It's working now.  I think I know what happened.   It was downloading and I logged into work through a secure server and that must have shut the TiVo download down.  Thanks again for your help.

**Comment by mackworth** [comment]
Great. Glad to hear it's works for you!

**Comment by mrfusiontm** [comment]
One more quick question  When I tried the link in your original reply (the
one to http://dvr-5d49.local.:80)
it comes up asking for a user name and password.  What user name and
password is it looking for?  my TiVo.com info? my local user info?
I don't remember ever setting up a user name and password on my TiVo
before....

**Comment by mackworth** [comment]
Sure. It's has a fixed username: "tivo" and the password is your MAK.
